// Generated by ios/fixtures/generate_cert.go. Do not edit by hand.
// Re-run: go run ios/fixtures/generate_cert.go > ios/Tests/LanyardCoreTests/GoCert.generated.swift
// Every value below is produced by the Go x509 implementation, so the
// Swift tests that consume it are real cross-implementation checks.

enum GoCertFixtures {
    static let seedHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    static let deviceName = "test-device"
    static let subjectCN = "LANyard test-device"
    static let serialHex = "f0123456789abcde0011223344556677"
    static let publicKeyHex = "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
    static let spkiHex = "302a300506032b657003210003a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
    static let fingerprint = "a050837d85070582ccf7394b0988847cc312cb88259b894899f6f239cf1791a5"
    static let derHex = "308201393081eca003020102021100f0123456789abcde0011223344556677300506032b6570301e311c301a060355040313134c414e7961726420746573742d646576696365301e170d3230303130323033303430355a170d3330303130323033303430355a301e311c301a060355040313134c414e7961726420746573742d646576696365302a300506032b657003210003a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8a33f303d300e0603551d0f0101ff040403020780301d0603551d250416301406082b0601050507030106082b06010505070302300c0603551d130101ff04023000300506032b65700341002b5dccff22c7f2781df244644e98f90dff04d4065ffed5a5e7a752b3d96b99123873c1665bf0de7954e8ed800e1cc8621f8a108bf20dd8490d3456007ac3620f"
    static let notBefore = "2020-01-02T03:04:05Z"
    static let notAfter = "2030-01-02T03:04:05Z"
    static let extKeyUsage = ["1.3.6.1.5.5.7.3.1", "1.3.6.1.5.5.7.3.2"]
    static let keyUsageDigitalSignature = true
    static let basicConstraintsCA = false
}
