// Generated by ios/fixtures/generate.go. Do not edit by hand.
// Re-run: go run ios/fixtures/generate.go > ios/Tests/LanyardCoreTests/GoFixtures.generated.swift
// The values below are produced by the Go implementation, so a Swift test
// comparing against them is a real cross-implementation check.

enum GoFixtures {
    struct Ed25519Vector {
        let name: String
        let seedHex: String
        let publicKeyHex: String
        let spkiHex: String
        let fingerprint: String
    }

    static let ed25519: [Ed25519Vector] = [
        Ed25519Vector(name: "zero", seedHex: "0000000000000000000000000000000000000000000000000000000000000000", publicKeyHex: "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", spkiHex: "302a300506032b65700321003b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", fingerprint: "339e2ff917630507b6a423b5ce084e285d1fa65d93b3e27a6195d3bbebc9ae23"),
        Ed25519Vector(name: "increment", seedHex: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", publicKeyHex: "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8", spkiHex: "302a300506032b657003210003a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8", fingerprint: "a050837d85070582ccf7394b0988847cc312cb88259b894899f6f239cf1791a5"),
        Ed25519Vector(name: "ff", seedHex: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", publicKeyHex: "76a1592044a6e4f511265bca73a604d90b0529d1df602be30a19a9257660d1f5", spkiHex: "302a300506032b657003210076a1592044a6e4f511265bca73a604d90b0529d1df602be30a19a9257660d1f5", fingerprint: "8d5eb75dbb64464ac9369d2416a026c99aad4ebf9cdb7c73adda86dd17815b0f"),
    ]

    struct SasVector {
        let fpA: String
        let fpB: String
        let nonceA: String
        let nonceB: String
        let code: String
    }

    static let sas: [SasVector] = [
        SasVector(fpA: "aaaa", fpB: "bbbb", nonceA: "11111111111111111111111111111111", nonceB: "22222222222222222222222222222222", code: "223062"),
        SasVector(fpA: "deadbeef", fpB: "cafebabe", nonceA: "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", nonceB: "f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0", code: "459339"),
        SasVector(fpA: "bbbb", fpB: "aaaa", nonceA: "22222222222222222222222222222222", nonceB: "11111111111111111111111111111111", code: "223062"),
        SasVector(fpA: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", fpB: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", nonceA: "11111111111111111111111111111111", nonceB: "22222222222222222222222222222222", code: "986280"),
        SasVector(fpA: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", fpB: "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210", nonceA: "00112233445566778899aabbccddeeff", nonceB: "ffeeddccbbaa99887766554433221100", code: "866599"),
    ]
}
