//go:build ignore

// Generates a Go-built Ed25519 self-signed certificate fixture for the Swift
// tests, so the "Swift parses a Go certificate" direction compares against
// values that come from Go rather than from hand-typed DER.
//
// Run from the repository root:
//
//	go run ios/fixtures/generate_cert.go > ios/Tests/LanyardCoreTests/GoCert.generated.swift
//
// It writes a Swift file; re-run it whenever the certificate template changes.
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"fmt"
	"math/big"
	"strings"
	"time"
)

func main() {
	seed := make([]byte, 32)
	for i := range seed {
		seed[i] = byte(i)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	serial, ok := new(big.Int).SetString("f0123456789abcde0011223344556677", 16)
	if !ok {
		panic("bad serial")
	}

	notBefore := time.Date(2020, 1, 2, 3, 4, 5, 0, time.UTC)
	notAfter := time.Date(2030, 1, 2, 3, 4, 5, 0, time.UTC)

	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "LANyard test-device"},
		NotBefore:             notBefore,
		NotAfter:              notAfter,
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
	}

	der, err := x509.CreateCertificate(rand.Reader, template, template, pub, priv)
	if err != nil {
		panic(err)
	}
	leaf, err := x509.ParseCertificate(der)
	if err != nil {
		panic(err)
	}
	spki := leaf.RawSubjectPublicKeyInfo
	sum := sha256.Sum256(spki)

	ekuOIDs := make([]string, 0, len(leaf.ExtKeyUsage))
	for _, u := range leaf.ExtKeyUsage {
		if oid, ok := oidFromExtKeyUsage(u); ok {
			ekuOIDs = append(ekuOIDs, oid)
		}
	}

	var b strings.Builder
	b.WriteString("// Generated by ios/fixtures/generate_cert.go. Do not edit by hand.\n")
	b.WriteString("// Re-run: go run ios/fixtures/generate_cert.go > ios/Tests/LanyardCoreTests/GoCert.generated.swift\n")
	b.WriteString("// Every value below is produced by the Go x509 implementation, so the\n")
	b.WriteString("// Swift tests that consume it are real cross-implementation checks.\n\n")
	b.WriteString("enum GoCertFixtures {\n")
	fmt.Fprintf(&b, "    static let seedHex = %q\n", hex.EncodeToString(seed))
	fmt.Fprintf(&b, "    static let deviceName = %q\n", "test-device")
	fmt.Fprintf(&b, "    static let subjectCN = %q\n", leaf.Subject.CommonName)
	fmt.Fprintf(&b, "    static let serialHex = %q\n", hex.EncodeToString(leaf.SerialNumber.Bytes()))
	fmt.Fprintf(&b, "    static let publicKeyHex = %q\n", hex.EncodeToString(pub))
	fmt.Fprintf(&b, "    static let spkiHex = %q\n", hex.EncodeToString(spki))
	fmt.Fprintf(&b, "    static let fingerprint = %q\n", hex.EncodeToString(sum[:]))
	fmt.Fprintf(&b, "    static let derHex = %q\n", hex.EncodeToString(der))
	fmt.Fprintf(&b, "    static let notBefore = %q\n", leaf.NotBefore.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "    static let notAfter = %q\n", leaf.NotAfter.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "    static let extKeyUsage = [%s]\n", quoteList(ekuOIDs))
	fmt.Fprintf(&b, "    static let keyUsageDigitalSignature = %t\n", leaf.KeyUsage&x509.KeyUsageDigitalSignature != 0)
	fmt.Fprintf(&b, "    static let basicConstraintsCA = %t\n", leaf.IsCA)
	b.WriteString("}\n")

	fmt.Print(b.String())
}

func quoteList(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}

func oidFromExtKeyUsage(u x509.ExtKeyUsage) (string, bool) {
	switch u {
	case x509.ExtKeyUsageServerAuth:
		return "1.3.6.1.5.5.7.3.1", true
	case x509.ExtKeyUsageClientAuth:
		return "1.3.6.1.5.5.7.3.2", true
	default:
		return "", false
	}
}
