//go:build ignore

// Generates the cross-implementation fixtures used by the Swift core tests, so
// the expected values come from the Go implementation itself rather than from
// hand-typed numbers. Run from the repository root:
//
//	go run ios/fixtures/generate.go > ios/Tests/LanyardCoreTests/GoFixtures.generated.swift
//
// It writes a Swift file; re-run it whenever the Go protocol changes.
package main

import (
	"crypto/ed25519"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"fmt"
	"strings"
)

func main() {
	var b strings.Builder
	b.WriteString("// Generated by ios/fixtures/generate.go. Do not edit by hand.\n")
	b.WriteString("// Re-run: go run ios/fixtures/generate.go > ios/Tests/LanyardCoreTests/GoFixtures.generated.swift\n")
	b.WriteString("// The values below are produced by the Go implementation, so a Swift test\n")
	b.WriteString("// comparing against them is a real cross-implementation check.\n\n")
	b.WriteString("enum GoFixtures {\n")

	// --- Ed25519 SPKI fingerprints (spec §3.1). -------------------------------
	b.WriteString("    struct Ed25519Vector {\n")
	b.WriteString("        let name: String\n        let seedHex: String\n        let publicKeyHex: String\n")
	b.WriteString("        let spkiHex: String\n        let fingerprint: String\n    }\n\n")
	b.WriteString("    static let ed25519: [Ed25519Vector] = [\n")

	seeds := []struct {
		name string
		seed []byte
	}{
		{"zero", bytes(0x00, 32)},
		{"increment", increments(32)},
		{"ff", bytes(0xff, 32)},
	}
	for _, s := range seeds {
		priv := ed25519.NewKeyFromSeed(s.seed)
		pub := priv.Public().(ed25519.PublicKey)
		spki, err := x509.MarshalPKIXPublicKey(pub)
		if err != nil {
			panic(err)
		}
		// The Ed25519 SPKI is a fixed 12-byte prefix followed by the raw 32-byte key.
		const prefix = "302a300506032b6570032100"
		if got := hex.EncodeToString(spki); !strings.HasPrefix(got, prefix) || len(got) != len(prefix)+64 {
			panic("unexpected Ed25519 SPKI shape: " + got)
		}
		sum := sha256.Sum256(spki)
		fmt.Fprintf(&b,
			"        Ed25519Vector(name: %q, seedHex: %q, publicKeyHex: %q, spkiHex: %q, fingerprint: %q),\n",
			s.name, hex.EncodeToString(s.seed), hex.EncodeToString(pub), hex.EncodeToString(spki), hex.EncodeToString(sum[:]),
		)
	}
	b.WriteString("    ]\n\n")

	// --- SAS vectors (spec §3.4). ---------------------------------------------
	b.WriteString("    struct SasVector {\n")
	b.WriteString("        let fpA: String\n        let fpB: String\n        let nonceA: String\n        let nonceB: String\n        let code: String\n    }\n\n")
	b.WriteString("    static let sas: [SasVector] = [\n")

	// Known desktop vectors (also asserted by the Kotlin SasTest), plus the
	// order-swapped and long/realistic-shape cases.
	sasCases := []struct{ fpA, fpB, nA, nB string }{
		{"aaaa", "bbbb", "11111111111111111111111111111111", "22222222222222222222222222222222"},
		{"deadbeef", "cafebabe", "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", "f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0"},
		{"bbbb", "aaaa", "22222222222222222222222222222222", "11111111111111111111111111111111"},
		{strings.Repeat("a", 64), strings.Repeat("b", 64), strings.Repeat("1", 32), strings.Repeat("2", 32)},
		{"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
			"fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
			"00112233445566778899aabbccddeeff", "ffeeddccbbaa99887766554433221100"},
	}
	for _, c := range sasCases {
		fmt.Fprintf(&b,
			"        SasVector(fpA: %q, fpB: %q, nonceA: %q, nonceB: %q, code: %q),\n",
			c.fpA, c.fpB, c.nA, c.nB, sas(c.fpA, c.fpB, c.nA, c.nB),
		)
	}
	b.WriteString("    ]\n")
	b.WriteString("}\n")

	fmt.Print(b.String())
}

// sas mirrors internal/identity.SAS exactly.
func sas(fpA, fpB, nonceA, nonceB string) string {
	a, b, na, nb := fpA, fpB, nonceA, nonceB
	if a > b {
		a, b, na, nb = b, a, nb, na
	}
	h := sha256.New()
	h.Write([]byte(a))
	h.Write([]byte{0})
	h.Write([]byte(b))
	h.Write([]byte{0})
	h.Write([]byte(na))
	h.Write([]byte{0})
	h.Write([]byte(nb))
	sum := h.Sum(nil)
	n := uint32(sum[0])<<24 | uint32(sum[1])<<16 | uint32(sum[2])<<8 | uint32(sum[3])
	return fmt.Sprintf("%06d", n%1_000_000)
}

func bytes(v byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = v
	}
	return out
}

func increments(n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = byte(i)
	}
	return out
}
